/*
* Copyright (c) 2020 - 2024 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier:  BSD-3-Clause
*/
#include <stdio.h>
#include "common_utils.h"
#include "main_application.h"
 #include "gpt_timer.h"
// Uncomment the desired debug level
#include "log_disabled.h"
//#include "log_error.h"
//#include "log_warning.h"
//#include "log_info.h"
//#include "log_debug.h"



 #ifdef  ENABLE_PWM_LED1
 void enable_Led1_PWM(void)
 {
 	fsp_err_t err = FSP_SUCCESS;
 	uint32_t gpt_desired_duty_cycle_percent = RESET_VALUE;
 	uint32_t gpt_desired_period_ms          = RESET_VALUE;
 	uint64_t period_counts                  = RESET_VALUE;
 	uint32_t pclkd_freq_hz                  = RESET_VALUE;
 	gpt_desired_duty_cycle_percent = LED1_DEFAULT_DUTY_CYCLE ; // edit here to change duty cycle
   log_debug( "LED1:Default Period:%d ms   Default Duty Cycle:%d \r\n", ((LED1_DEFAULT_PERIOD* 1000) /SET_PERIOD_1_SECS),LED1_DEFAULT_DUTY_CYCLE);

 	/* Validate Duty cycle percentage */
 	if (GPT_MAX_PERCENT < gpt_desired_duty_cycle_percent)
 	{
 		log_error ("\r\n ** LED1:INVALID INPUT, DESIRED DUTY CYCLE IS OUT OF RANGE. ** \r\n");
 	}
 	else
 	{
 			/* we got valid input, Initialize PWM timer */
 			err = init_gpt_timer(&g_timer_pwm_led1_ctrl, &g_timer_pwm_led1_cfg);
 			if(FSP_SUCCESS != err)
 			{
 				log_error("** LED1:GPT TIMER INIT FAILED ** \r\n");
 			}
 			log_debug("LED1:Opened Timer in PWM Mode\r\n");

 			/* Start PWM Timer*/
 			err = start_gpt_timer(&g_timer_pwm_led1_ctrl);
 			if(FSP_SUCCESS != err)
 			{
 				log_error("** LED1:GPT TIMER START FAILED ** \r\n");
 				/*Close PWM Timer instance */
 				deinit_gpt_timer(&g_timer_pwm_led1_ctrl);
 			}
 			log_debug("LED1:Started Timer in PWM Mode\r\n");

 		/* Set DutyCycle and period of PWM timer */
 			err = set_timer_Period_and_Dutycycle(LED1_DEFAULT_PERIOD,gpt_desired_duty_cycle_percent,&g_timer_pwm_led1_ctrl);
 			if(FSP_SUCCESS != err)
 			{
 				/* GPT Timer DutyCycleSet Failure message */
 				log_error ("\r\n ** LED1:Timer Period and Dutycycle SET FAILED ** \r\n");
 				/*Close PWM Timer instance */
 				deinit_gpt_timer(&set_timer_Period_and_Dutycycle);
 			}
 	}
 }
 #endif

 #ifdef  ENABLE_PWM_LED2
 void enable_Led2_PWM(void)
 {
 	fsp_err_t err = FSP_SUCCESS;
 	uint32_t gpt_desired_duty_cycle_percent = RESET_VALUE;
 	uint32_t gpt_desired_period_ms          = RESET_VALUE;
 	uint64_t period_counts                  = RESET_VALUE;
 	uint32_t pclkd_freq_hz                  = RESET_VALUE;
 	gpt_desired_duty_cycle_percent = LED2_DEFAULT_DUTY_CYCLE ; // edit here to change duty cycle
   log_debug( "LED2:Default Period:%d ms   Default Duty Cycle:%d \r\n", ((LED2_DEFAULT_PERIOD* 1000) /SET_PERIOD_1_SECS),LED2_DEFAULT_DUTY_CYCLE);

 	/* Validate Duty cycle percentage */
 	if (GPT_MAX_PERCENT < gpt_desired_duty_cycle_percent)
 	{
 		log_error ("\r\n ** LED2:INVALID INPUT, DESIRED DUTY CYCLE IS OUT OF RANGE. ** \r\n");
 	}
 	else
 	{
 			/* we got valid input, Initialize PWM timer */
 			err = init_gpt_timer(&g_timer_pwm_led2_ctrl, &g_timer_pwm_led2_cfg);
 			if(FSP_SUCCESS != err)
 			{
 				log_error("** LED2:GPT TIMER INIT FAILED ** \r\n");
 			}
 			log_debug("LED2:Opened Timer in PWM Mode\r\n");

 			/* Start PWM Timer*/
 			err = start_gpt_timer(&g_timer_pwm_led2_ctrl);
 			if(FSP_SUCCESS != err)
 			{
 				log_error("** LED2:GPT TIMER START FAILED ** \r\n");
 				/*Close PWM Timer instance */
 				deinit_gpt_timer(&g_timer_pwm_led2_ctrl);
 			}
 			log_debug("Started Timer in PWM Mode\r\n");

 		err = set_timer_Period_and_Dutycycle(LED2_DEFAULT_PERIOD,gpt_desired_duty_cycle_percent,&g_timer_pwm_led2_ctrl);
 		if(FSP_SUCCESS != err)
 		{
 			/* GPT Timer DutyCycleSet Failure message */
 			log_error ("\r\n ** LED2:Timer Period and Dutycycle SET FAILED ** \r\n");
 			/*Close PWM Timer instance */
 			deinit_gpt_timer(&set_timer_Period_and_Dutycycle);
 		}
 	}
 }
 #endif

void main_application(void) {
// Start of autogenerated code

 #if defined(ENABLE_LED1) && defined(ENABLE_PWM_LED1)
  enable_Led1_PWM();
 #endif

 #if defined(ENABLE_LED2) && defined(ENABLE_PWM_LED2)
  enable_Led2_PWM();
 #endif


	while(true)
	  {
		// do nothing
	  }
	// End of autogenerated code
}

