/*
* Copyright (c) 2020 - 2024 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier:  BSD-3-Clause
*/
#include <stdio.h>
#include "common_utils.h"
#include "main_application.h"
#include "icu_ep.h"
// Uncomment the desired debug level
#include "log_disabled.h"
//#include "log_error.h"
//#include "log_warning.h"
//#include "log_info.h"
//#include "log_debug.h"
 volatile bool g_sw_press = false;
 
void main_application(void) {
 
// Start of autogenerated code
   fsp_err_t err = FSP_SUCCESS;
   uint8_t led_state = 1;
 
  /* Initialize External IRQ driver*/
  log_debug("** ICU ICU Stack ** \r\n");
  err = icu_init();
  /* Handle error */
  if(FSP_SUCCESS != err)
  {
    log_error("** ICU INIT FAILED ** \r\n");
  }
 
  /* Enable External IRQ driver*/
  err = icu_enable();
  /* Handle error */
  if(FSP_SUCCESS != err)
  {
    log_error("** ICU ENABLE FAILED ** \r\n");
    /* Close External IRQ module.*/
    icu_deinit();
  }
 
 
 
 
  while(true)
  {
   if(g_sw_press == true)
    {
 #ifdef ENABLE_LED1
      if(led_state)
      {
          utils_set_LED(LED1_LED, BSP_IO_LEVEL_HIGH);
          log_debug("** LED1 ON ** \r\n");
      }
      else
      {
          utils_set_LED(LED1_LED, BSP_IO_LEVEL_LOW);
          log_debug("** LED1 OFF ** \r\n");
      }
 #endif
 
 #ifdef ENABLE_LED2
      if(led_state)
      {
          utils_set_LED(LED2_LED, BSP_IO_LEVEL_HIGH);
          log_debug("** LED2 ON ** \r\n");
      }
      else
      {
          utils_set_LED(LED2_LED, BSP_IO_LEVEL_LOW);
          log_debug("** LED2 OFF ** \r\n");
      }
 #endif
      led_state= !led_state;
      g_sw_press = false;
    }
 }
// End of autogenerated code
 
}
 
// Start of autogenerated code
 void user_button_callback( external_irq_callback_args_t * p_args)
 {
    if (p_args->channel == USER_SW1_IRQ_NUMBER)
    {
      g_sw_press = true;
      log_debug("** S1 Switch Pressed ** \r\n");
    }
 }
// End of autogenerated code

